#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bielzpoddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bielzapipod
  template:
    metadata:
      labels:
        app: bielzapipod
    spec:
      containers:
        - name: bielzapipod
          image: bielz/kubeapi:latest
          ports:
            - containerPort: 8080
---
#LoadBalance
apiVersion: v1
kind: Service
metadata:
  name: bielzpodservice
spec:
  selector:
    app: bielzapipod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
