apiVersion: v1
kind: Service
metadata:
  name: bielzlb
  labels:
    app: bielzlb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: bielzapipod
